name: dlstm-cicd

on:
  push:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - name: run django test
        run: | 
          python src/manage.py test

