name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.dev.HOST }}
        username: ${{ secrets.dev.USERNAME }}
        key: ${{ secrets.dev.PRIVATE_KEY }}
        port: 22
        script: whoami
