name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - name: CD
      #  run: echo 'CD is Disabled (Check workflow comment for the code).'
       - name: Deploy using ssh
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.PRIVATE_KEY }}
           port: 22
           script: |
             cd ~/dlstm-lab
             git pull origin master
             git status

  deploy:

    runs-on: ubuntu-latest
    steps:
    - name: Build django dependencies
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/dlstm-lab
          git pull origin -f master
          git status
          source bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test
