name: Django CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
            cd ~/dlstm-lab
            ls
            git pull origin -f master
            git status

            source bin/activate
            pip install -r requirements.txt
            sudo systemctl restart dlstm 
            echo "DEPLOYMENT SUCCESS!"
