name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: ssh key passphrase
        run: |
          ${{ secrets.HOST }}
        # uses: appleboy/ssh-action@v0.1.6
        # with:
        # host: ${{ secrets.HOST }}
        # username: ${{ secrets.USERNAME }}
        # key: ${{ secrets.PRIVATE_KEY }}
        # port: 22
        # script: |
        # whoami
        # ls -al
