name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.10]

    steps:
    - name: Build django dependencies
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ~/dlstm-lab
          git pull origin -f master
          git status
          source bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test
