name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v0.1.6
      - shell: bash
        run: | 
          echo ${{ secrets.HOST }} ${{ secrets.USERNAME }}

  deploy:

    runs-on: ubuntu-latest
    steps:
    - name: Build django dependencies
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/dlstm-lab
          git pull origin -f master
          git status
          source bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

    - name: Run Tests
      run: |
        python manage.py test
